@startuml
!include .\\Circulo.puml
!include .\\Mundo.puml
!include .\\Objeto.puml
!include .\\Poligono.puml
!include .\\Ponto.puml
!include .\\Program.puml
!include .\\Retangulo.puml
!include .\\SegReta.puml
!include .\\Spline.puml
!include .\\SrPalito.puml
!include .\\obj\Debug\net6.0\win-x64\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Debug\net6.0\win-x64\CG_N3.AssemblyInfo.puml
@enduml
